# Generated by Django 5.0.2 on 2024-02-26 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('time_date', models.DateTimeField()),
                ('skill', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=50)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finder.company')),
            ],
        ),
    ]
